### ISSUE TITLE
Make cycle graphics in story section larger

### ISSUE THREAD

**Issue by jlthibault** [noahmanger/thejusticetrap#10]
**Current size**
White space feels like it's overwhelming the cycle

![screen shot 2016-04-09 at 1 12 48 pm](https://cloud.githubusercontent.com/assets/5427577/14405108/008eef78-fe55-11e5-822f-1379442fbffb.png)

**Improved size**
Trying to get it to take up a more proportional sense of space

![screen shot 2016-04-09 at 1 16 24 pm](https://cloud.githubusercontent.com/assets/5427577/14405119/51630dbc-fe55-11e5-92ae-a4f81be6b5bf.png)

**Comment by noahmanger** [comment]
How's this? 
![image](https://cloud.githubusercontent.com/assets/1696495/14413210/ad6e088c-ff27-11e5-80bd-4fb1645cd36d.png)

**Comment by jlthibault** [comment]
:+1:
