### ISSUE TITLE
Clear dotted lines from copy area

### ISSUE THREAD

**Issue by jlthibault** [noahmanger/thejusticetrap#11]
The copy around the cycle graphic at the end got a bit longer, and grew into the dotted line. I don't mind when the lines overlap the cycle, but let's try to keep them clear of any text:

![screen shot 2016-04-09 at 1 18 12 pm](https://cloud.githubusercontent.com/assets/5427577/14405135/afb06b1c-fe55-11e5-887f-d851c4ab66e3.png)

**Comment by noahmanger** [comment]
👍 
![image](https://cloud.githubusercontent.com/assets/1696495/14413219/e5181516-ff27-11e5-8be1-11c28fa81cb2.png)

**Comment by jlthibault** [comment]
Niiiiiice :+1:
