### ISSUE TITLE
Draw stronger connection between opening slide and text below it

### ISSUE THREAD

**Issue by jlthibault** [noahmanger/thejusticetrap#12]
I've been thinking about this, and I really don't want to add in any sort of visual gimmick or other clutter on that first opening video scene.

They also don't want to move the text up to that first slide.

I'm thinking that maybe the best approach would be to reduce the top padding above the `It targets the poor and people of color, churns out guilty pleas...` and raise the whole box to just slightly above the fold again so that some of the text is visible. (Sorry, I know this reverts a previous design change). Something close to this?

![screen shot 2016-04-09 at 1 29 08 pm](https://cloud.githubusercontent.com/assets/5427577/14405185/165e939c-fe57-11e5-856b-770d56385b46.png)

What do you think @noahmanger ?

**Comment by noahmanger** [comment]
Works for me! 
![image](https://cloud.githubusercontent.com/assets/1696495/14413180/dc092024-ff26-11e5-8966-96400a666991.png)

**Comment by jlthibault** [comment]
:+1:
