### ISSUE TITLE
Build placeholder for Recidivism video

### ISSUE THREAD

**Issue by jlthibault** [noahmanger/thejusticetrap#9]
This video is being released in the coming weeks, so we should build in a placeholder for it now:
### Mobile

**Current mobile:**

![screen shot 2016-04-09 at 12 35 46 pm](https://cloud.githubusercontent.com/assets/5427577/14405060/d7b6d76a-fe53-11e5-86f9-d5430c549144.png)

**Adjusted mobile:**
(it would be ideal to cut down the space above the header if we can)
![screen shot 2016-04-09 at 1 04 47 pm](https://cloud.githubusercontent.com/assets/5427577/14405065/e5de255a-fe53-11e5-81a9-ea7ef174da73.png)
### Desktop

**Two options**
I'm not sure which is easier to build based off the mobile mockups above, but I like that the second options reduces the overlap space so that more of the image is visible

![screen shot 2016-04-09 at 1 05 17 pm](https://cloud.githubusercontent.com/assets/5427577/14405067/12e6b896-fe54-11e5-8370-cec12463651e.png)

![screen shot 2016-04-09 at 1 05 37 pm](https://cloud.githubusercontent.com/assets/5427577/14405068/12e76462-fe54-11e5-9349-eee43b18fff0.png)

The button would be deactivated for all of these

**Comment by noahmanger** [comment]
So the simplest solution to this is just basically keep it the same on desktop:
![image](https://cloud.githubusercontent.com/assets/1696495/14413305/ea0830bc-ff2a-11e5-8c6c-387c0a314f52.png)

But then do what you designed for mobile:
![image](https://cloud.githubusercontent.com/assets/1696495/14413318/4adc15fc-ff2b-11e5-8a7d-445eb6b34f3f.png)

That work for you?

**Comment by noahmanger** [comment]
Actually on an iPhone 5-size screen, it's cut off: 
![image](https://cloud.githubusercontent.com/assets/1696495/14416436/f1bb7362-ff5e-11e5-8dfb-08148480f12b.png)

**Comment by jlthibault** [comment]
D'oh! The screenshot I took & edited for mobile was really a condensed desktop window. Sorry bout that.

What about breaking text to two lines for each button on mobile? Does that help it fit into 1/4 grid-wide buttons?

**Comment by noahmanger** [comment]
Ah yep! That does it:

![image](https://cloud.githubusercontent.com/assets/1696495/14449838/c8d5241a-002c-11e6-97c4-bc7a51d43115.png)

**Comment by jlthibault** [comment]
This was previously resolved by https://github.com/noahmanger/thejusticetrap/pull/14/commits/d7fdcfa413b56fd68cb3e0b768813cb0d8c2063c
